/*
 * File: "rpc_client_dbg.h".
 * This file was autogenerated from "rpc.vsidl" file.
 * This file will NOT overwriten.
 * You may (and must) edit this file safely.
 */
//----------------------------------------------------------------------------
#include <stdio.h> // fprintf()
#include "vsrpc.h" // vsrpc_error_str()
//----------------------------------------------------------------------------
#define VSRPC_ERROR_DBG(err, rpc) \
  fprintf(stderr, "VSRPC error %i: '%s'\n", err, vsrpc_error_str(err));
//----------------------------------------------------------------------------
